version: "2"         # required to adjust maintainability checks
plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "17"
      minimum_severity: major
      tests_patterns:
        - src/test/**
        - src/integration-test/**
  duplication:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: false
  pep8:
    enabled: true
  radon:
    enabled: true
  sonar-python:
    enabled: true
  pmd:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
  - "config/"
  - "scripts/"
  - "test-automation/"
  - "backend/target"
  - "db/"
  - "backend/dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "**/*.d.ts"
  - "**/*.test.tsx"
  - "**/*.test.ts"
